model:
  gaussian:
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 3
      optimization:
        means_lr_init: 0.0001
        means_lr_scheduler:
          lr_final: 0.000001
          max_steps: 30000
        scales_lr: 0.005
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 0.5
        final_factor: 0.005
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
      depth_ratio: 1.0
      diable_trimming: true
  density: internal.density_controllers.citygsv2_density_controller.CityGSV2DensityController
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  path: /vol/data/Crofts_Lot
  parser:
    class_path: EstimatedDepthBlockColmap